
Tracker:AddLocations("locations/R First Floor.json")
Tracker:AddLocations("locations/R Second Floor.json")
Tracker:AddLocations("locations/R Third Floor.json")
Tracker:AddLocations("locations/UF Upper.json")
Tracker:AddLocations("locations/UF Middle.json")
Tracker:AddLocations("locations/UF Lower.json")
Tracker:AddLocations("locations/R Basement.json")
Tracker:AddLocations("locations/Outside RPD.json")
Tracker:AddLocations("locations/S Entrance.json")
Tracker:AddLocations("locations/S Upper.json")
Tracker:AddLocations("locations/S Middle.json")
Tracker:AddLocations("locations/S Lower.json")
Tracker:AddLocations("locations/L B1.json")
Tracker:AddLocations("locations/L B2 East.json")
Tracker:AddLocations("locations/L B2 West.json")
Tracker:AddLocations("locations/L B3.json")